### ISSUE TITLE
4.5 Gitデーモンのページで一箇所 `daemon` が `deamon` になっている

### ISSUE THREAD

**Issue by Roadagain** [progit/progit2-ja#104]
重箱の隅をつつくようで申し訳ありませんが、一応ファイル名の誤記なのでご報告します。

https://github.com/progit/progit2-ja/blob/34a99ee963a50225c9baa61e14ace6d52164b49a/book/04-git-server/sections/git-daemon.asc#L100

英語版では正しく `git-daemon-export-ok` と表記されているのでタイポだと思われます。
https://github.com/progit/progit2/blob/6e09183f057c615084698261ce4c7b616dd8b582/book/04-git-server/sections/git-daemon.asc#L92

なお、 `deamon` でリポジトリ内検索をかけたところ他の箇所はヒットしませんでした。

**Comment by harupong** [comment]
ご指摘ありがとうございます。
