### ISSUE TITLE
Appendix Aの翻訳開始

### ISSUE THREAD

**Issue by satob** [progit/progit2-ja#43]
Appendix Aの翻訳をしたいと思います。
どれだけ時間が取れるかわかりませんが……

**Comment by harupong** [comment]
:tada:

WIPでプッシュされている内容でばっちりですので、このままよろしくお願いします :bow: 

メンテナー自身も7章の作業がすっかり停滞中なので、時間の件はお気になさらず。まったり進行でいきましょう :tea:

**Comment by harupong** [comment]
自動ビルドが失敗してるので、解決するまでクローズせずこのままにしておきます。

**Comment by harupong** [comment]
日本語のビルドがうまくいくようになりました！ 画像の代替テキスト部分にダブルクォテーションが使われていたことが失敗の原因だったようです 11486151ac9e
