### ISSUE TITLE
Wrong encoding on visual studio file

### ISSUE THREAD

**Issue by schacon** [progit/progit2-ja#50]
It appears that the file:

https://github.com/progit/progit2-ja/blob/master/book/A-git-in-other-environments/sections/visualstudio.asc

Is improperly encoded, or has at least one character in it that is not in the UTF-8 range. It is causing the Atlas builds to break. I'll try to figure out a CI process or something that can check for this in the future, but to get the [builds](https://progit.org/translations/lang/ja) working again, someone will have to re-encode it in UTF-8.

**Comment by schacon** [comment]
Sorry, I opened this because Atlas informed me that this file was the issue. I cannot, however, recreate the problem locally or figure out which byte sequence is the offending one. I've reached out to Atlas and I'll try to get a definitive answer.

**Comment by schacon** [comment]
Ah, so this isn't really the issue, it was a different problem which is addressed in #51. Closing this.

**Comment by harupong** [comment]
Sorry for all the hassle :coffee:

**Comment by schacon** [comment]
Not a problem at all!
