### ISSUE TITLE
Chaconさんが来日

### ISSUE THREAD

**Issue by harupong** [progit/progit2-ja#54]
6月2～3日にグランドプリンスホテル新高輪で開催される[AWS Summit Tokyo 2015](http://www.awssummit.tokyo/)に合わせて、Pro Gitの著者であるScott Chaconさんが来日されるそうです。初日のKeynoteでトークも予定されています http://www.awssummit.tokyo/devcon.html#KEY-02

参加登録は無料、締め切りは5/28までだそうです。原著者と会う機会はなかなかありませんので、お時間あれば会場まで足を運んでみてはいかがでしょうか。

cc @m-takagi @satob

**Comment by m-takagi** [comment]
:+1: 

実は一昨年の http://github-onlab.peatix.com/ にも来ていらしたので、京都会場でお話を聞いてました。
早口でたたみかけるようにしゃべりまくるので、聞き取るのが大変だった記憶が :smile:

**Comment by satob** [comment]
情報ありがとうございます。
残念ですが、当日はちょっと仕事の都合がつきそうにないです……

**Comment by harupong** [comment]
一昨年もいらしてたんですね。実は親日家なのかな……Twitterを見てると鮨好きではあるようですね :sushi: 

折角の機会なので、本にサインしてもらいたいなぁ、と思ったりしております。

**Comment by m-takagi** [comment]
そういえば、いつぞやのRubyKaigiにも出ていらしたよなあ…と思って調べてみたら、こんなのを見つけました。

http://rubykaigi.org/2009/ja/talks/17H01

**Comment by harupong** [comment]
結局参加できずでした...残念
