### ISSUE TITLE
Git-bashを使っているのにプロンプトがPowerShell

### ISSUE THREAD

**Issue by satob** [progit/progit2-ja#64]
http://git-scm.com/book/ja/v2/Git-and-Other-Systems-Migrating-to-Git#TFS
地の文では「Git-bash  environment」で実行していると記載があるが、プロンプトがPowerShellになっている。

**Comment by harupong** [comment]
![snapcrab_noname_2015-7-23_18-45-10_no-00](https://cloud.githubusercontent.com/assets/204623/8847573/f880ece4-316a-11e5-9829-bb453408ed8b.png)

この部分でしょうか。原文とコマンドの内容から読み解くと、

- git コマンドはPowerShell上で実行している
- シングルクォートで囲われた部分のsed コマンドは、Git-bash environment で実行している

ってことじゃないかと思いました。

**Comment by satob** [comment]
Windows 7で試してみました。
なるほど、msysgit上でgitを実行した場合、内部からコマンドをキックする際は起動元のshellではなく、同梱のGit bashが使われるんですね。納得しました。

＃ただ、実際には最後から二番目の引数「--」をダブルクォートで囲む必要がありました。
＃囲まないと引数が正しく認識されず、gitがfilterコマンドのusageを出力して終了ｓルウ

**Comment by harupong** [comment]
Windows環境で確認していただいたのですね、ありがとうございます。[公式ドキュメント](http://git-scm.com/docs/git-filter-branch) `--msg-filter` に以下のような記述がありました。

    The argument is evaluated in the shell 

ここでいうshellはPOSIX準拠のshell、msysgit的には `sh.exe` や `bash.exe` ってことなんでしょうね、きっと。

もう一点、-- をダブルクォーテーションでエスケープする必要がある件ですが、progit/progit2 に修正プルリクエストを送ってみてはいかがでしょう？本家Contributersに名を連ねるチャンス！！

**Comment by harupong** [comment]
fixed at upstream https://github.com/progit/progit2/pull/363

@satob ナイスプルリク！！ :tada:
