### ISSUE TITLE
Pro Git日本語版第2版サイトの公開準備

### ISSUE THREAD

**Issue by harupong** [progit/progit2-ja#69]
![image](https://cloud.githubusercontent.com/assets/204623/9731357/67bdccd8-5657-11e5-9710-c9b9b0cad120.png)

↑**ついに100%達成！！**の記念スクショ

------------------

@m-takagi さん、 @satob さん、これまでの作業ありがとうございました。

翻訳作業が完了しましたので、第2版の「ランディングページ」っぽいもの作ろうと思っています。被リンク数が多く検索でも上位にくる初版電子書籍公開サイト https://progit-ja.github.io を修正する形にする予定です。

リポジトリを progit/progit2-ja に統合できないのが唯一のデメリットだと思っていますが、なにかありましたらお知らせください。

## TODO

- [x] 未訳部分の翻訳
    - [x] contribution
    - [x] index
    - [x] introduction
- [x] 公開サイトの準備
  - [x] 初版サイト progit-ja.github.io をベースに、適宜修正する
    - [x] 第2版の特徴に触れる
    - [x] Ben への言及
    - [x] 電子書籍データへのリンク修正
    - [x] 問い合わせ先の見直し
  - [x] 初版サイトの最新版をタグ付けしておく
- [x] アナウンスする前に片付けたい問題 #66

**Comment by m-takagi** [comment]
:+1: *100

途中から完全に任せっきりになってしまってすみませんでした…。

**Comment by harupong** [comment]
とんでもない、ここまで来れたのはみなさんのおかげです。ご協力ありがとうございました :smile: 

で、冒頭部分に数ページ未訳箇所があるのを発見してしまったので、アナウンスはもう少し先になりそうです…… :sweat_smile:

**Comment by harupong** [comment]
未訳部分を翻訳し、https://progit-ja.github.io を更新しました。これにて一旦完了です :tada:
