### ISSUE TITLE
git-scm.comで「中央集権型のワークフロー」の図が表示されない

### ISSUE THREAD

**Issue by satob** [progit/progit2-ja#82]
http://git-scm.com/book/ja/v2/Git-%E3%81%A7%E3%81%AE%E5%88%86%E6%95%A3%E4%BD%9C%E6%A5%AD-%E5%88%86%E6%95%A3%E4%BD%9C%E6%A5%AD%E3%81%AE%E6%B5%81%E3%82%8C
で、「Figure 5-1. 中央集権型のワークフロー」の図が表示されていません。
PDF版の方では正しく表示されているのですが、システムの不具合か何かでしょうか？

**Comment by harupong** [comment]
報告ありがとうございます。調べてみたら progit/progit2 のほうでも[何度か取り上げられてる](https://github.com/progit/progit2/search?q=Centralized+workflow&type=Issues&utf8=%E2%9C%93)みたいです。

[git-scm.comのほうのissue](https://github.com/git/git-scm.com/pull/505)もたっていますが、もう何ヶ月も放置されてますね......

**Comment by harupong** [comment]
本件を修正してくれるはずの↑のPRがマージされましたが、git-scm.comのほうにデプロイされてないようです……

**Comment by YueLinHo** [comment]
It shows again. This issue can be closed now.

**Comment by harupong** [comment]
@YueLinHo Thanks for the reminder! Also, kudos to the recent works on Pro Git project :smile:

**Comment by YueLinHo** [comment]
@harupong  ありがとうございます
My first Japan sentence using JP-Hiragana input `a ri ga to u go za i ma su`, and it is for you. :smile:

**Comment by harupong** [comment]
:heart_eyes:
