### ISSUE TITLE
複数チャプターに渡り未翻訳箇所や誤記などまとめ

### ISSUE THREAD

**Issue by chuntaro** [progit/progit2-ja#83]
ほとんど重箱の隅ばかりですみません…。
7章まで読んでとても参考になりました。
翻訳作業されてる(もちろん原著を作成をされている)関係者の方々に感謝します。
ありがとうございます！
残りの章は(内容がマニアックなので…)おいおい読むとして、気付いた点をいったんまとめました。
ご確認ください。

04-git-server/sections/git-daemon.asc

　フルパスをしていしなくても → フルパスを指定しなくても
　(※ 若干読みづらいので漢字の方がいいです)

　Gitosis → git-shell
　(※ 原文だとgit-shellと書いてありますが、Gitosisはどこから来たのでしょうか…)

04-git-server/sections/git-on-a-server.asc

　サーバー SSH アクセス可能なアカウント → サーバーに SSH でアクセス

05-distributed-git/sections/contributing.asc

　At this point, で始まる原文は未訳のまま表示されています

06-github/sections/1-setting-up-account.asc

　これはとても需要です。 → これはとても重要です。

07-git-tools/sections/revision-selection.asc

　ブランチを持っている場合など「で、この → ブランチを持っている場合などで、「この

**Comment by harupong** [comment]
重箱の隅つつきこそが訳文改善の一番の近道！ということで、ご指摘ありがとうございました～ :smile:

**Comment by harupong** [comment]
> (※ 原文だとgit-shellと書いてありますが、Gitosisはどこから来たのでしょうか…)

https://github.com/progit/progit2/pull/232 の訳文への反映漏れですね。初版にはあったGitosisの節が第2版では削除されたのでした。

**Comment by chuntaro** [comment]
対応ありがとうございます！
ただ、07-git-tools/sections/revision-selection.ascの修正がうまく行ってませんでした。
一応コミットログにコメントを追加しましたが、伝わったでしょうか？

**Comment by harupong** [comment]
コメントありがとうございました。8章以降も誤訳や珍訳が潜んでいると思いますので、なにかお気づきでしたらぜひお知らせください :bow: （プルリクエスト大歓迎です～ :grin: )
