### ISSUE TITLE
第3章：「追跡ブランチ」が二つの意味で使われている

### ISSUE THREAD

**Issue by unarist** [progit/progit2-ja#90]
`/book/03-git-branching/sections/remote-branches.asc` より引用。

```
//////////////////////////
Checking out a local branch from a remote-tracking branch automatically creates what is called a ``tracking branch'' (or sometimes an ``upstream branch'').
Tracking branches are local branches that have a direct relationship to a remote branch.
If you're on a tracking branch and type `git pull`, Git automatically knows which server to fetch from and branch to merge into.
//////////////////////////
追跡ブランチからローカルブランチにチェックアウトすると、``追跡ブランチ'' (あるいは ``上流ブランチ'') というブランチが自動的に作成されます。
追跡ブランチとは、リモートブランチと直接のつながりを持つローカルブランチのことです。
追跡ブランチ上で `git pull` を実行すると、Git は自動的に取得元のサーバーとブランチを判断します。
```

この段落までの「追跡ブランチ」は原文の `remote-tracking branch` を指していたのが、これ以降は原文の `tracking branch` を指すようになっています。特に境目であるこの段落では、訳文の1行目と2・3行目で意味が変わっています。

別の訳語を当てた方が混乱しないかと思うのですが、どうでしょうか？

**Comment by harupong** [comment]
仰るとおりですね。ご指摘ありがとうございます。 3378e04 の変更を訳文に取り込んだ際、訳文を更新していなかったようです。

1. remote branch → リモートブランチ（リモートサーバーにあるブランチ）
1. remote-tracking branch → リモート追跡ブランチ
1. tracking branch → 追跡ブランチ


というふうに区別するよう、修正したいと思います（PR大歓迎です :grin: ）。

**Comment by harupong** [comment]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">Pro Gitの日本語訳、「tracking branch」と「remote-tracking branch」の両方を「追跡ブランチ」と訳していて、どちらがどのブランチなのか区別できない</p>&mdash; mizdra (@mizdra) <a href="https://twitter.com/mizdra/status/691920860647669760">2016, 1月 26</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by harupong** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">Git の「リモート追跡ブランチ」「リモートブランチ」「追跡ブランチ」「上流ブランチ」が混用されてるのつらい、 Pro Git Book でさえ tracking branch と upstream branch を同一視してる <a href="https://t.co/vN6pXHO70j">https://t.co/vN6pXHO70j</a></p>&mdash; 歯車たちの社会 (@uasi) <a href="https://twitter.com/uasi/status/696653236015493120">2016, 2月 8</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by uasi** [comment]
> Pro Git Book でさえ tracking branch と upstream branch を同一視してる

これに関しては原文のほうを修正してPRを出しておきました。 https://github.com/progit/progit2/pull/519
