### ISSUE TITLE
ベアリポジトリが「クマ」とまぎらわしい

### ISSUE THREAD

**Issue by marutosi** [progit/progit2-ja#98]
v1 issue: https://github.com/progit/progit/issues/951

http://www.redmine.org/issues/23108

ベア is confusing with bear (クマ).
"ベアリポジトリ" should be "ベア(bare)リポジトリ" at least first use.

**Comment by harupong** [comment]
Nice catch!! I've modified the first appearance of this phrase, which is at Chapter4 https://github.com/progit/progit2-ja/commit/34a99ee963a50225c9baa61e14ace6d52164b49a.

**Comment by harupong** [comment]
Please note the following two things.

1. Neither v1 manuscript nor ja translation are maintained any more. Please close v1 issue you've created.
1. There is an ongoing deployment issue with the v2, which is been followed at https://github.com/progit/progit2/issues/625. This change won't be applied to git-scm.com until things get sorted out.

**Comment by marutosi** [comment]
I have closed https://github.com/progit/progit/issues/951.

**Comment by harupong** [comment]
@marutosi thanks a lot!
